# config.yaml
project:
  name: lstm_stock_predictor
  seed: 42

data:
  lookback: 60          # number of past days to use as input
  predict_horizon: 10   # number of days to predict (we will average them)
  interval: 15minute
  train_from: '2024-09-01 09:15:00'
  train_to: '2025-03-01 15:30:00'
  inference_window_days: 5  # minimum fetch window; auto-raised to satisfy the longest EMA
  feature_cols:
    - open
    - high
    - low
    - close
  local_csv: ../data/ind_nifty10list.csv

training:
  re-train: True
  batch_size: 32
  epochs: 20
  validation_split: 0.1
  model_save_path: ../models
  scaler_save_path: ../scalers

kite:
  api_key: "usvvbzqq7736z01b"
  api_secret: "ocq3i8e9sfn9bp7876lf6lib14g0czih"
  request_token: "3wNFjtk5DcHT0O96IEt6hYrv7yYKL8yN"
  access_token: "cdDYsM3hgmJQ3oOV72iGxYlE8CUMLw1F"   # after login; can be updated
  api_url: "https://api.kite.trade/session/token"
  instrument_token_map:
    RELIANCE: 738561  # example, replace with correct instrument tokens

